/* --------------------------------------------------------------
 * auth0_wrapper.js
 *
 * NOTE: this file was generated by proton lumo ai. It may not be correct.
 *
 * This file:
 *   • Loads the Auth0 SPA SDK from the CDN (or you can npm‑install it).
 *   • Instantiates a single Auth0 client (you can extend it to support many).
 *   • Exposes a small set of functions that Gleam can call.
 *
 * The functions are attached to `globalThis.__auth0_wrapper__` so that
 * Gleam’s `@external` calls can find them.
 * ------------------------------------------------------------ */

import {
  Error,
  Ok,
} from "./gleam.mjs";

(() => {
  // -----------------------------------------------------------------
  // 1️⃣ Load the Auth0 SDK
  // -----------------------------------------------------------------
  // The CDN version ships as a UMD bundle that registers `createAuth0Client`
  // on the global object.  We load it dynamically to keep the file usable
  // both in browsers and in Node (for server‑side rendering tests).
  // -----------------------------------------------------------------
  const SDK_URL = "https://cdn.auth0.com/js/auth0-spa-js/2.11/auth0-spa-js.development.js";

  // Helper to inject a <script> tag when running in a browser.
  function loadSdkInBrowser() {
    return new Promise((resolve, reject) => {
      if (typeof window === "undefined") {
        reject(new Error("Not a browser environment"));
        return;
      }
      const script = document.createElement("script");
      script.src = SDK_URL;
      script.async = true;
      script.onload = () => resolve(window.createAuth0Client);
      script.onerror = (e) => reject(new Error(`Failed to load Auth0 SDK: ${e.message}`));
      document.head.appendChild(script);
    });
  }

  // Helper for Node / environments that support `fetch`.
  async function loadSdkInNode() {
    const response = await fetch(SDK_URL);
    if (!response.ok) {
      throw new Error(`Failed to fetch Auth0 SDK (${response.status})`);
    }
    const code = await response.text();
    // Evaluate the UMD bundle in the current context.
    // eslint-disable-next-line no-eval
    eval(code);
    // After evaluation the global `createAuth0Client` function is defined.
    return globalThis.createAuth0Client;
  }

  // Unified loader – picks the right strategy based on environment.
  async function loadAuth0Sdk() {
    if (typeof window !== "undefined") {
      return loadSdkInBrowser();
    }
    // Assume a modern Node environment with fetch support.
    return loadSdkInNode();
  }

  // -----------------------------------------------------------------
  // 2️⃣ Internal state
  // -----------------------------------------------------------------
  /** @type {import("@auth0/auth0-spa-js").Auth0Client | null} */
  let auth0Client = null;

  // -----------------------------------------------------------------
  // 3️⃣ Public FFI functions
  // -----------------------------------------------------------------
  const ffi = {
    /**
     * Initialise the Auth0 client.
     *
     * @param {Object} config  – Same shape as Auth0ClientOptions.
     * @returns {Promise<string>} – Resolves to a client identifier (always "default").
     */
    async init(config) {
      if (auth0Client !== null) {
        // Re‑initialising is a no‑op; you could also throw if you prefer.
        return Ok("default");
      }
      const createClient = await loadAuth0Sdk();
      auth0Client = await createClient(config);
      return Ok("default");
    },

    /**
     * Perform a login using a redirect flow.
     *
     * @param {Object} [options] – Optional login options.
     * @returns {Promise<boolean>} – Resolves to true when the navigation was triggered.
     */
    async loginWithRedirect(options = {}) {
      if (!auth0Client) {
        throw new Error("Auth0 client not initialised – call init/1 first");
      }
      await auth0Client.loginWithRedirect(options);
      return Ok(true);
    },

    /**
     * Called on the redirect‑callback page to finish the login.
     *
     * @returns {Promise<Object>} – The Auth0 token payload.
     */
    async handleRedirectCallback() {
      if (!auth0Client) {
        throw new Error("Auth0 client not initialised");
      }
      const result = await auth0Client.handleRedirectCallback();
      return Ok(result); // usually contains appState, etc.
    },

    /**
     * Silently obtain an access token.
     *
     * @param {Object} [options] – Optional token request options.
     * @returns {Promise<string>} – The access token.
     */
    async getTokenSilently(options = {}) {
      if (!auth0Client) {
        throw new Error("Auth0 client not initialised");
      }
      const token = await auth0Client.getTokenSilently(options);
      return Ok(token);
    },

    /**
     * Retrieve the currently authenticated user profile (if any).
     *
     * @returns {Promise<Object | null>}
     */
    async getUser() {
      if (!auth0Client) {
        throw new Error("Auth0 client not initialised");
      }
      const user = await auth0Client.getUser();
      return Ok(user ?? null);
    },

    /**
     * Log out the current session.
     *
     * @param {Object} [options] – Optional logout options.
     * @returns {Promise<boolean>}
     */
    async logout(options = {}) {
      if (!auth0Client) {
        throw new Error("Auth0 client not initialised");
      }
      await auth0Client.logout(options);
      return Ok(true);
    },
  };

  // -----------------------------------------------------------------
  // 4️⃣ Export the namespace for Gleam
  // -----------------------------------------------------------------
  // Gleam looks for functions under `globalThis.__gleam_external__` by default.
  // To keep things tidy we create a dedicated namespace.
  // -----------------------------------------------------------------
  if (!globalThis.__auth0_wrapper__) {
    globalThis.__auth0_wrapper__ = {};
  }
  Object.assign(globalThis.__auth0_wrapper__, ffi);
})();